### ISSUE TITLE
Could not find the requested service glusterd: host

### ISSUE THREAD

**Issue by patsevanton** [gluster/gluster-ansible-cluster#21]
Hello
i try install gluster on centos 7.6
Get error: Could not find the requested service glusterd: host

```
cat ansible.cfg 
[defaults]
inventory = hosts
remote_user = centos
host_key_checking = False
stdout_callback=debug
```

```
cat hosts
[gluster_servers]
gluster1 ansible_ssh_host=172.26.9.65
gluster2 ansible_ssh_host=172.26.9.67
gluster3 ansible_ssh_host=172.26.9.66
```

```
cat playbook.yml 
---
- name: Create Gluster cluster
  hosts: gluster_servers
  remote_user: centos
  gather_facts: false

  vars:
    # gluster volume
    gluster_cluster_hosts:
      - 172.26.9.65
      - 172.26.9.67
      - 172.26.9.66
    gluster_cluster_volume: testvol
    gluster_cluster_transport: 'tcp'
    gluster_cluster_force: 'yes'
    gluster_cluster_bricks: '/mnt/brick1/store,/mnt/brick2/store'

    # variables to create specific type of the volume
    gluster_cluster_replica_count: 3

    # variables to set specific volume options
    gluster_cluster_options: 'performance.cache-size:256MB'

  roles:
    - gluster.cluster
```

```
TASK [gluster.cluster/roles/gluster_volume : Start glusterd on the nodes if not already started] *************************************************************************************************************
failed: [gluster1 -> 172.26.9.65] (item=172.26.9.65) => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "ansible_loop_var": "item", 
    "changed": false, 
    "item": "172.26.9.65"
}

MSG:

Could not find the requested service glusterd: host

failed: [gluster1 -> 172.26.9.67] (item=172.26.9.67) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "item": "172.26.9.67"
}

MSG:

Could not find the requested service glusterd: host

failed: [gluster1 -> 172.26.9.66] (item=172.26.9.66) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "item": "172.26.9.66"
}

MSG:

Could not find the requested service glusterd: host
```
